version: '3.5'

services:
  iroha:
    image: hyperledger/iroha:latest
    container_name: iroha
    depends_on:
      - iroha-postgres
    # restart: always
    tty: true
    environment:
      - KEY=keys/node0
      - IROHA_POSTGRES_HOST=localhost
      - IROHA_POSTGRES_PORT=5432
      - IROHA_POSTGRES_USER=postgres
      - IROHA_POSTGRES_PASSWORD=mysecretpassword
    entrypoint:
      - /opt/iroha_data/entrypoint.sh
    network_mode: host
    volumes:
      - ./iroha:/opt/iroha_data
    ports:
      - 50051:50051
      - 10001:10001
    #logging:
    #   driver: none

  iroha-postgres:
    image: postgres:9.5
    container_name: iroha-postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=postgres
    network_mode: host
    ports:
     - 5432:5432
    #logging:
    #  driver: none